// Automatically generated by astro-icon
// 9a9e79f21014b0bd34b0e990a6abb0bde75f9a5eb56d7160ffa36e350f5fbc06

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "Facebook"
		| "Github"
		| "Instagram"
		| "Menu"
		| "Moon"
		| "Sun";
}