// Automatically generated by astro-icon
// 15c27ec65b1aef9e862a1ee416f83748492cd2193e57aec47a5a8fbaa1b90bf8

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "Linkedin"
		| "Menu"
		| "Moon"
		| "Sun";
}